export const TagSet = function(tag) {
    switch(tag) {
        case 'CC': return 'Coordinating conj.'
        case 'CD': return 'Cardinal number'
        case 'DT': return 'Determiner'
        case 'EX': return 'Existential there'
        case 'FW': return 'Foreign word'
        case 'IN': return 'Preposition'
        case 'JJ': return 'Adjective'
        case 'JJR': return 'Adjective, comparative'
        case 'JJS': return 'Adjective, superlative'
        case 'LS': return 'List item marker'
        case 'MD': return 'Modal'
        case 'NN': return 'Noun, singular or mass'
        case 'NNS': return 'Noun, plural'
        case 'NNP': return 'Proper noun, singular'
        case 'NNPS': return 'Proper noun, plural'
        case 'PDT': return 'Predeterminer'
        case 'POS': return 'Possessive ending'
        case 'PRP': return 'Personal pronoun'
        case 'PP$': return 'Possessive pronoun'
        case 'RB': return 'Adverb'
        case 'RBR': return 'Adverb, comparative'
        case 'RBS': return 'Adverb, superlative'
        case 'RP': return 'Particle'
        case 'SYM': return 'Symbol'
        case 'TO': return 'infinitival to'
        case 'UH': return 'Interjection'
        case 'VB': return 'Verb, base form'
        case 'VBD': return 'Verb, past tense'
        case 'VBG': return 'Verb, gerund/present pple'
        case 'VBN': return 'Verb, past participle'
        case 'VBP': return 'Verb, non-3rd ps. sg. present'
        case 'VBZ': return 'Verb, 3rd ps. sg. present'
        case 'WDT': return 'Wh-determiner'
        case 'WP': return 'Wh-pronoun'
        case 'WP$': return 'Possessive wh-pronoun'
        case 'WRB': return 'Wh-adverb'
        default:
            return tag
    }
}